export const membershipTiers = [
  {
    id: "starter",
    name: "Starter",
    nameZh: "尝新会员",
    topUp: 999,
    bonus: 100,
    bonusPercent: 10,
    giftedValue: 100,
    gifts: [
      { en: "1 scalp analysis", zh: "1次头皮检测" },
      { en: "1 skin analysis", zh: "1次皮肤检测" },
    ],
  },
  {
    id: "enjoy",
    name: "Enjoy",
    nameZh: "悦享会员",
    topUp: 2000,
    bonus: 268,
    bonusPercent: 13,
    giftedValue: 248,
    gifts: [
      { en: "1 scalp analysis", zh: "1次头皮检测" },
      { en: "1 × 75-min Korean Classic Head Spa", zh: "1次75mins韩式经典头疗" },
    ],
  },
  {
    id: "premium",
    name: "Premium",
    nameZh: "臻享会员",
    topUp: 5000,
    bonus: 788,
    bonusPercent: 16,
    giftedValue: 515,
    gifts: [
      { en: "1 scalp analysis", zh: "1次头皮检测" },
      { en: "1 × 30-min Korean Glass-Skin Peel", zh: "1次30mins韩国水光焕肤酸疗" },
      { en: "1 × 75-min Korean Classic Head Spa", zh: "1次75mins韩式经典头疗" },
      { en: "1 × 75-min Korean Manual Facial Sculpting", zh: "1次75mins韩式徒手小颜护理" },
    ],
  },
  {
    id: "royal",
    name: "Royal",
    nameZh: "至臻会员",
    topUp: 10000,
    bonus: 1999,
    bonusPercent: 20,
    giftedValue: 985,
    gifts: [
      { en: "1 scalp analysis + 1 skin analysis", zh: "1次头皮检测 + 1次皮肤检测" },
      { en: "1 × 75-min Hair-Loss Revitalising Treatment", zh: "1次75mins脱发焕活护理" },
      { en: "1 × 90-min Korean Aqua-Glow Treatment", zh: "1次90mins韩式水光炸弹管理" },
      { en: "1 × 120-min Full-Body Fat-Burning Mind & Body Reset", zh: "1次120mins全身燃脂身心重启管理" },
    ],
  },
] as const;

export const membershipTerms = [
  {
    id: "validity",
    title: "Validity",
    titleZh: "有效期",
    body: "The top-up amount, bonus amount and gifted items are valid for two years from the top-up date.",
    bodyZh: "充值金额、赠送金额及赠送项目，自充值之日起有效期为两年。",
  },
  {
    id: "refunds-sharing",
    title: "Refunds & sharing",
    titleZh: "退款与共享",
    body: "Top-up amounts are non-refundable. The account balance may be transferred to or shared with family members.",
    bodyZh: "充值金额不予退款；账户余额可转让或与家人共享使用。",
  },
  {
    id: "balance-use",
    title: "Balance use",
    titleZh: "余额使用",
    body: "The top-up amount and bonus amount are combined into one account balance, with no required order of use. The balance may be used for all services and products.",
    bodyZh: "充值金额与赠送金额合并为同一账户余额，不设使用先后顺序；余额适用于所有服务及产品。",
  },
  {
    id: "service-pricing",
    title: "Service pricing",
    titleZh: "服务计价",
    body: "Services paid with the member balance are charged at single-treatment prices and cannot be combined with package pricing or other member discounts.",
    bodyZh: "使用会员余额支付服务时，按单次项目价格计费，不可与疗程套价或其他会员折扣同时使用。",
  },
  {
    id: "birthday-benefit",
    title: "Birthday benefit",
    titleZh: "生日月礼遇",
    body: "Members receive 30% off one service during their birthday month, with no service or amount limit. This benefit cannot be combined with other member discounts or promotions.",
    bodyZh: "会员生日当月可享一次单项服务七折优惠，不限服务项目及金额；不可与其他会员折扣或促销活动同时使用。",
  },
  {
    id: "gifted-items",
    title: "Gifted items",
    titleZh: "赠送项目",
    body: "Gifted items are fixed and cannot be exchanged or converted to cash. Please contact the studio if you need to postpone their use.",
    bodyZh: "赠送项目为固定内容，不可更换或折现；如需延期使用，请联系门店。",
  },
] as const;
